#+TITLE:Lernjournal
#+AUTHOR:Patrick Günthard
#+DATE: 5ia13c Berufbildungsschule Winterthur
* <2016-09-06>

** Gemacht

   Wir haben angefangen, die verschiedenen Komponenten welche wir verwenden wollen, herunterzuladen und 
   das Projekt aufzusetzten.

 
* <2016-09-13> 
** Gemacht

   Ich habe an der Web-Applikation weitergearbeitet. Ich arbeite schon seit einigen Tagen daran gearbeitet.
   Heute habe ich die Login- und Signup funktion fertig implementiert und getestet. Ich habe auch begonnen, 
   eine logout funktion zu implementieren.
   

** Was habe ich gelernt?

   Ich habe nichts neues hinzugelernt, da ich alle dinge welche ich implementiert habe, schon einmal
   gemacht habe.

* <2016-09-20>
** Gemacht

   Heute habe ich am Backend gearbeitet. Ich habe weiter Rest-Services implementiert.

* <2016-09-27>

** Gemacht

   Heute habe ich am Frontend weitergearbeitet. Ich habe auch recherchiert, wie man mit *node js* einen file-upload zum laufen bringen kann.

** Was Ich heute gelernt habe

   Ich habe mich mit File Upload mit node js beschäftigt und gelernt, wie dieser funktioniert.

* <2016-10-04>


** Gemacht

   Ich habe weiter an der Upload Funktion gearbeitet. Ich habe sowohl am Frontend und am 
   Backend versucht, die nötigen methoden zu implementieren. Ich habe es jedoch nicht fertig
   geschafft.

** Was Ich heute gelernt habe

   Ich habe heute mehr über HTML-Forms und Ajax in AngularJS gelernt.
