#!/bin/bash
#
# NAME
#   filediff - show differences between files
# SYNOPSIS
#   filediff file1 file2
#
#
# (c) 2015 by Patrick Günthard
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

file1=""
file2=""

file1lines=()
file2lines=()

file1length=0
file2length=0

filelongerlength=0
diffcounter=0


difffiles()
{
    while IFS='' read -r line || [[ -n "$line" ]]; do
	file1lines+=("$line")
    done < "$file1"

    while IFS='' read -r line || [[ -n "$line" ]]; do
	file2lines+=("$line")
    done < "$file2"

    file1length=${#file1lines[@]}
    file2length=${#file2lines[@]}
    
    if [ $file1length -gt $file2length ]
    then
	filelongerlength=$file1length
    else
	filelongerlength=$file2length
    fi

    for ((i = 0; i < $filelongerlength; i++))
    do
	if [ $file1length -lt $i ]
	then
	    echo ${file2lines[$i]}
	    diffcounter=$((diffcounter + 1))
	elif [ $file2length -lt $i ]
	then
	    echo ${file1lines[$i]}
	    diffcounter=$((diffcounter + 1))
	elif [ ${file1lines[$i]} != ${file2lines[$i]} ]
	then
	    echo "${file1lines[$i]} | ${file2lines[$i]}"
	    diffcounter=$((diffcounter + 1))
	fi
    done

    if [ $diffcounter -eq 0 ]
    then
	echo "file has no differences"
    elif [ $diffcounter -eq 1 ]
    then
	echo "there is 1 difference in this files"
    else
	echo "there are $diffcounter differences in this files"
    fi
}


if [ ! $# -eq 2 ]
then
    echo "Invalid number of paramenters. Usage: filediff [file1] [file2]"
else
    file1=$1
    file2=$2

    difffiles

fi
