DROP DATABASE IF EXISTS DB_ANTI_SOCIAL;

CREATE DATABASE DB_ANTI_SOCIAL;

USE DB_ANTI_SOCIAL;

CREATE TABLE TAS_ACCOUNT(
  ACCOUNT_ID    INTEGER     NOT NULL AUTO_INCREMENT,
  USER_NAME     VARCHAR(64) NOT NULL,
  PASSWORD      VARCHAR(64) NOT NULL,
  DATE_OF_BIRTH DATE        NOT NULL,
  FIRST_NAME    VARCHAR(64) NOT NULL,
  LAST_NAME     VARCHAR(64) NOT NULL,

  PRIMARY KEY(ACCOUNT_ID)
);

CREATE TABLE TAS_GENDER(
  GENDER_ID           INTEGER     NOT NULL AUTO_INCREMENT,
  GENDER_DESCRIPTION  VARCHAR(64) NOT NULL,

  PRIMARY KEY(GENDER_ID)
);

CREATE TABLE TAS_ROLE(
  ROLE_ID           INTEGER     NOT NULL AUTO_INCREMENT,
  ROLE_DESCRIPTION  VARCHAR(64) NOT NULL,

  PRIMARY KEY(ROLE_ID)
);

CREATE TABLE  TAS_ACCOUNT_ROLES(
  ACCOUNT_ROLES_ID  INTEGER NOT NULL AUTO_INCREMENT,
  ACCOUNT_ID        INTEGER NOT NULL,
  ROLE_ID           INTEGER NOT NULL,

  PRIMARY KEY(ACCOUNT_ROLES_ID)
);

CREATE TABLE TAS_GROUP(
  GROUP_ID    INTEGER     NOT NULL AUTO_INCREMENT,
  GROUP_NAME  VARCHAR(64) NOT NULL,

  PRIMARY KEY(GROUP_ID)
);

CREATE TABLE  TAS_ACCOUNT_GROUP(
  ACCOUNT_GROUP_ID  INTEGER NOT NULL AUTO_INCREMENT,
  ACCOUNT_ID        INTEGER NOT NULL,
  GROUP_ID          INTEGER NOT NULL,

  PRIMARY KEY(ACCOUNT_GROUP_ID)
);

CREATE TABLE TAS_ACCOUNT_STATUS(
  ACCOUNT_STATUS_ID INTEGER NOT NULL AUTO_INCREMENT,
  STATUS_TEXT       VARCHAR(64) NOT NULL,
  ACCOUNT_ID        INTEGER NOT NULL,

  PRIMARY KEY(ACCOUNT_STATUS_ID)
);

CREATE TABLE TAS_POST(
  POST_ID       INTEGER       NOT NULL AUTO_INCREMENT,
  POST_TITLE    VARCHAR(128)  NOT NULL,
  POST_CONTENT  VARCHAR(8192) NOT NULL,
  ACCOUNT_ID    INTEGER       NOT NULL,

  PRIMARY KEY(POST_ID)
);

CREATE TABLE TAS_TAG(
  TAG_ID    INTEGER     NOT NULL  AUTO_INCREMENT,
  TAG_NAME  VARCHAR(32) NOT NULL,

  PRIMARY KEY(TAG_ID)
);

CREATE TABLE TAS_POST_TAG(
  POST_TAG_ID INTEGER NOT NULL AUTO_INCREMENT,
  POST_ID     INTEGER NOT NULL,
  TAG_ID      INTEGER NOT NULL,

  PRIMARY KEY(POST_TAG_ID)
);

CREATE TABLE TAS_COMMENT(
  COMMENT_ID      INTEGER       NOT NULL AUTO_INCREMENT,
  COMMENT_CONTENT VARCHAR(256)  NOT NULL,
  POST_ID         INTEGER       NOT NULL,
  ACCOUNT_ID      INTEGER       NOT NULL,

  PRIMARY KEY(COMMENT_ID)
);

CREATE TABLE TAS_LIKE(
  LIKE_ID       INTEGER NOT NULL AUTO_INCREMENT,
  POST_ID       INTEGER NOT NULL,
  ACCOUNT_ID    INTEGER NOT NULL,
  LIKE_TYPE_ID  INTEGER NOT NULL,

  PRIMARY KEY(LIKE_ID)
);

CREATE TABLE TAS_LIKE_TYPE(
  LIKE_TYPE_ID INTEGER        NOT NULL AUTO_INCREMENT,
  LIKE_TYPE_NAME  VARCHAR(64) NOT NULL,

  PRIMARY KEY(LIKE_TYPE_ID)
);
